flux FluxRW weight_flux_all 1
xsec_multi RW weight_All_UBGenie 1

xsec_AxFFCCQEshape RW weight_AxFFCCQEshape_UBGenie 1
xsec_DecayAngMEC RW weight_DecayAngMEC_UBGenie 1
xsec_NormCCCOH RW weight_NormCCCOH_UBGenie 1
xsec_NormNCCOH RW weight_NormNCCOH_UBGenie 1
xsec_RPA_CCQE RW weight_RPA_CCQE_UBGenie 1
xsec_ThetaDelta2NRad RW weight_ThetaDelta2NRad_UBGenie 1
xsec_Theta_Delta2Npi RW weight_Theta_Delta2Npi_UBGenie 1
xsec_VecFFCCQEshape RW weight_VecFFCCQEshape_UBGenie 1
xsec_XSecShape_CCMEC RW weight_XSecShape_CCMEC_UBGenie 1

MRDEff RW weight_MRDUnc 1
DirtScale RW weight_DirtUnc 1

MCstats MCstat
BNBstats BNBstat

detVarShiftE1 DV detVarShiftE1
detVarShiftE2 DV detVarShiftE2
detVarShiftE3 DV detVarShiftE3
detVarShiftE4 DV detVarShiftE4
detVarShiftE5 DV detVarShiftE5
detVarShiftE6 DV detVarShiftE6
detVarShiftE7 DV detVarShiftE7
detVarShiftE8 DV detVarShiftE8
detVarShiftE9 DV detVarShiftE9
detVarShiftE10 DV detVarShiftE10
detVarShiftE11 DV detVarShiftE11
detVarShiftE12 DV detVarShiftE12
detVarShiftE13 DV detVarShiftE13
detVarShiftE14 DV detVarShiftE14
detVarShiftE15 DV detVarShiftE15
detVarShiftE16 DV detVarShiftE16
detVarShiftE17 DV detVarShiftE17
detVarShiftE18 DV detVarShiftE18
detVarShiftE19 DV detVarShiftE19
detVarShiftE20 DV detVarShiftE20
detVarShiftE21 DV detVarShiftE21
detVarShiftE22 DV detVarShiftE22
detVarShiftE23 DV detVarShiftE23
detVarShiftE24 DV detVarShiftE24
detVarShiftE25 DV detVarShiftE25
detVarShiftE26 DV detVarShiftE26
detVarShiftE27 DV detVarShiftE27
detVarShiftE28 DV detVarShiftE28
detVarShiftE29 DV detVarShiftE29
detVarShiftE30 DV detVarShiftE30
detVarShiftE31 DV detVarShiftE31
detVarShiftE32 DV detVarShiftE32
detVarShiftE33 DV detVarShiftE33
detVarShiftE34 DV detVarShiftE34
detVarShiftE35 DV detVarShiftE35
detVarShiftE36 DV detVarShiftE36
detVarShiftE37 DV detVarShiftE37
detVarShiftE38 DV detVarShiftE38
detVarShiftE39 DV detVarShiftE39
detVarShiftE40 DV detVarShiftE40
detVarShiftE41 DV detVarShiftE41
detVarShiftE42 DV detVarShiftE42
detVarShiftE43 DV detVarShiftE43
detVarShiftE44 DV detVarShiftE44
detVarShiftE45 DV detVarShiftE45
detVarShiftE46 DV detVarShiftE46
detVarShiftE47 DV detVarShiftE47
detVarShiftE48 DV detVarShiftE48
detVarShiftE49 DV detVarShiftE49
detVarShiftE50 DV detVarShiftE50
detVarShiftE51 DV detVarShiftE51
detVarShiftE52 DV detVarShiftE52
detVarShiftE53 DV detVarShiftE53
detVarShiftE54 DV detVarShiftE54
detVarShiftE55 DV detVarShiftE55
detVarShiftE56 DV detVarShiftE56
detVarShiftE57 DV detVarShiftE57
detVarShiftE58 DV detVarShiftE58
detVarShiftE59 DV detVarShiftE59
detVarShiftE60 DV detVarShiftE60

POT MCFullCorr 0.02
numTargets MCFullCorr 0.01

xsec_unisim sum 9 xsec_AxFFCCQEshape xsec_DecayAngMEC xsec_NormCCCOH
  xsec_NormNCCOH xsec_RPA_CCQE xsec_ThetaDelta2NRad xsec_Theta_Delta2Npi
  xsec_VecFFCCQEshape xsec_XSecShape_CCMEC

xsec_total sum 2 xsec_multi xsec_unisim

MCCal sum 2 MRDEff DirtScale

detVar_shift_total sum 60 detVarShiftE1 detVarShiftE2 detVarShiftE3 detVarShiftE4 detVarShiftE5 
  detVarShiftE6 detVarShiftE7 detVarShiftE8 detVarShiftE9 detVarShiftE10 
  detVarShiftE11 detVarShiftE12 detVarShiftE13 detVarShiftE14 detVarShiftE15 
  detVarShiftE16 detVarShiftE17 detVarShiftE18 detVarShiftE19 detVarShiftE20 
  detVarShiftE21 detVarShiftE22 detVarShiftE23 detVarShiftE24 detVarShiftE25 
  detVarShiftE26 detVarShiftE27 detVarShiftE28 detVarShiftE29 detVarShiftE30 
  detVarShiftE31 detVarShiftE32 detVarShiftE33 detVarShiftE34 detVarShiftE35 
  detVarShiftE36 detVarShiftE37 detVarShiftE38 detVarShiftE39 detVarShiftE40 
  detVarShiftE41 detVarShiftE42 detVarShiftE43 detVarShiftE44 detVarShiftE45 
  detVarShiftE46 detVarShiftE47 detVarShiftE48 detVarShiftE49 detVarShiftE50 
  detVarShiftE51 detVarShiftE52 detVarShiftE53 detVarShiftE54 detVarShiftE55 
  detVarShiftE56 detVarShiftE57 detVarShiftE58 detVarShiftE59 detVarShiftE60 

detVar_total sum 2 MCCal detVar_shift_total

total sum 7 xsec_total flux MCstats BNBstats detVar_total POT numTargets
