xsec_multi RW weight_All_UBGenie 1

xsec_AxFFCCQEshape RW weight_AxFFCCQEshape_UBGenie 1
xsec_DecayAngMEC RW weight_DecayAngMEC_UBGenie 1
xsec_NormCCCOH RW weight_NormCCCOH_UBGenie 1
xsec_NormNCCOH RW weight_NormNCCOH_UBGenie 1
xsec_RPA_CCQE RW weight_RPA_CCQE_UBGenie 1
xsec_ThetaDelta2NRad RW weight_ThetaDelta2NRad_UBGenie 1
xsec_Theta_Delta2Npi RW weight_Theta_Delta2Npi_UBGenie 1
xsec_VecFFCCQEshape RW weight_VecFFCCQEshape_UBGenie 1
xsec_XSecShape_CCMEC RW weight_XSecShape_CCMEC_UBGenie 1

MCstats MCstat

xsec_unisim sum 9 xsec_AxFFCCQEshape xsec_DecayAngMEC xsec_NormCCCOH
  xsec_NormNCCOH xsec_RPA_CCQE xsec_ThetaDelta2NRad xsec_Theta_Delta2Npi
  xsec_VecFFCCQEshape xsec_XSecShape_CCMEC

xsec_total sum 2 xsec_multi xsec_unisim

total sum 2 xsec_total MCstats
